### ISSUE TITLE
Go 1.11 modules support

### ISSUE THREAD

**Issue by jk-gan** [si3nloong/raptor#17]
We should start using go modules to manage packages
- [Modules](https://github.com/golang/go/wiki/Modules)
- [Go Modules in 2019](https://blog.golang.org/modules2019)

**Comment by si3nloong** [comment]
Fixed [50528861e222e7617af11eb01581e4f1324a52de](https://github.com/si3nloong/raptor/commit/50528861e222e7617af11eb01581e4f1324a52de)
